sv_stopwords = list(set(['tjugoen', 'fyra', 'gärna', 'ha', 'ändå', 'långsam', 'komma', 'tar', 'går', 'både', 'gått', 'bara', 'oss', 'man', 'sjuttonde', 'ska', 'båda', 'rätt', 'ligger', 'gör', 'ur', 'alltid', 'men', 'tack', 'fått', 'dagen', 'alltså', 'bort', 'sextio', 'fall', 'upp', 'andra', 'eller', 'följande', 'godast', 'hellre', 'mest', 'behövde', 'överst', 'övre', 'som', 'mina', 'mer', 'eftersom', 'inför', 'med', 'hade', 'tolfte', 'förlåt', 'nittio', 'rakt', 'sätt', 'viktig', 'enligt', 'ta', 'beslutat', 'någonting', 'ger', 'likställda', 'annat', 'femtio', 'tjungo', 'redan', 'längre', 'knappast', 'vänstra', 'mittemot', 'åtta', 'dom', 'ingenting', 'nitton', 'allas', 'de', 'hela', 'noll', 'mycket', 'tror', 'snart', 'sedan', 'några', 'enkla', 'långsammast', 'för', 'första', 'nedersta', 'lättare', 'bli', 'nej', 'ofta', 'säger', 'likställd', 'ibland', 'varken', 'ut', 'vara', 'sagt', 'dit', 'heller', 'sina', 'nödvändig', 'tills', 'gälla', 'procent', 'dessa', 'beslutit', 'var', 'godare', 'åttionde', 'fanns', 'delen', 'inget', 'kvar', 'den', 'ner', 'dagar', 'långt', 'åttonde', 'imorgon', 'hit', 'är', 'själv', 'femton', 'hon', 'efter', 'nittionde', 'kunnat', 'också', 'verkligen', 'tro', 'alla', 'sitt', 'dina', 'elva', 'dig', 'enkel', 'sen', 'lilla', 'står', 'och', 'möjligen', 'blev', 'tog', 'ser', 'nödvändigt', 'igår', 'högst', 'er', 'vilka', 'sex', 'kunde', 'varför', 'allt', 'nödvändigtvis', 'inga', 'olikt', 'våra', 'fin', 'tjugotre', 'ännu', 'nionde', 'tredje', 'samma', 'nummer', 'helst', 'adertonde', 'trettionde', 'ni', 'hennes', 'varsågod', 'tre', 'gäller', 'fast', 'liten', 'litet', 'fem', 'tillsammans', 'slutligen', 'gjorde', 'idag', 'andras', 'mellan', 'bäst', 'ett', 'blivit', 'innan', 'fjärde', 'nödvändiga', 'sent', 'mig', 'in', 'sade', 'något', 'hur', 'hundraett', 'en', 'honom', 'senast', 'små', 'tidigt', 'vad', 'ditt', 'tjugoett', 'vårt', 'mitt', 'värre', 'dagarna', 'stort', 'än', 'över', 'borta', 'ja', 'fyrtio', 'sjunde', 'utanför', 'trettio', 'på', 'vem', 'bra', 'här', 'dess', 'sjutton', 'han', 'genast', 'inom', 'om', 'varit', 'nittonde', 'stor', 'sig', 'sista', 'hjälp', 'jämfört', 'trettonde', 'kom', 'gjort', 'vår', 'bättre', 'vidare', 'högre', 'min', 'god', 'varifrån', 'gick', 'nu', 'stora', 'måste', 'fram', 'möjlig', 'nog', 'gång', 'hög', 'vänster', 'sjätte', 'tvåhundra', 'bådas', 'borde', 'jag', 'sexton', 'siste', 'finnas', 'nr', 'större', 'sjuttionde', 'sist', 'genom', 'bakom', 'höger', 'kan', 'längst', 'tolv', 'då', 'göra', 'kommer', 'att', 'dag', 'artonde', 'enkelt', 'denna', 'kommit', 'gott', 'så', 'även', 'många', 'två', 'hundra', 'era', 'få', 'oftast', 'femtonde', 'goda', 'därför', 'blir', 'långsamt', 'tio', 'femte', 'viktigt', 'tjugotvå', 'mindre', 'ert', 'femtionde', 'nästa', 'säga', 'någon', 'nån', 'tjugonde', 'tidig', 'dock', 'möjligtvis', 'lägga', 'fick', 'lite', 'framför', 
'henne', 'till', 'din', 'senare', 'annan', 'gällt', 'samt', 'fyrtionde', 'nåt', 'vi', 'nio', 'flesta', 'helt', 'ursäkt', 'vilken', 'dem', 'tionde', 'skall', 'vet', 'olika', 'heter', 'mera', 'långsammare', 'kanske', 'vems', 'åtminstone', 'fler', 'från', 'skulle', 'viktigare', 'behövas', 'ge', 'kr', 'möjligt', 'elfte', 'sämst', 'sextionde', 'ute', 'lätt', 'tjugo', 'beslut', 'nedre', 'flera', 'gå', 'lika', 'nya', 'väl', 'inuti', 'tidigare', 'inte', 'sextonde', 'sämre', 'haft', 'kunna', 'kolla', 'legat', 'adjö', 'aderton', 'nederst', 'ned', 'förra', 'före', 'inne', 'hans', 'tretton', 'sjuttio', 'ligga', 'minst', 'finns', 'mot', 'deras', 'ettusen', 'viktigast', 'smått', 'det', 'åttio', 'tidigast', 'där', 'varje', 'menar', 'har', 'visst', 'du', 'övermorgon', 'all', 'sju', 'behöva', 'bland', 'störst', 'i', 'ingen', 'vid', 'del', 'kör', 'sin', 'lättast', 'utan', 'aldrig', 'vilket', 'behövt', 'artonn', 'får', 'av', 'när', 'igen', 'hundraen', 'vill', 'fjortonde', 'året', 'under', 'skriver', 'fjorton', 'detta', 'länge', 'vart',
# Above is standard words, below are words we added
'åt', 'vare', 'vars', 'vore', 'gav', 'apropå', 'sådant', 'ju', 'valt',
'se', 'sett', 'hör', 'ses', 'säg', 'knappt', 'drygt', 'låter', 'stund', 'medan', 'låg', 'sa',
'låg', 'ställs', 'stå', 'övrig', 'ab', 'gånger', '1980-tal', 'år', 'ej', 'f.n.', 'kl.',
'år', 'kl', 'åring', 'sätt', 'person', 'årsålder', 'dag', 'tid', 'gång', 'sak', 'minut', 'sekund', 'timme', 'nent', '•', '✓', 'människa', 'del', 'de', 'fl', 
'sd', 'mp', 'kd', 'quot', ';s', 'vecka', 'månad'
]))

eng_stopwords = ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"]

stopwords = sv_stopwords + eng_stopwords